
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: nginx
          image: madacsbotondpal/nginx:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: "/var/index"
              name: task-pv-storage
