apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxserver
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nfs-volume
          nfs:
           server: 10.0.2.15
           path: /mnt/sharedfolder
      containers:
        - name: nginx
          image: madacsbotondpal/nginx:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: "/var/index"
              name: nfs-volume
