apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: nginx
      image: madacsbotondpal/nginx:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 80
      volumeMounts:
        - mountPath: "/var/index"
          name: task-pv-storage
